# Generated by Django 4.1.2 on 2022-10-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('rg', models.CharField(max_length=9)),
                ('cpf', models.CharField(max_length=11)),
                ('data_nascimento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('codigo_curso', models.CharField(max_length=10)),
                ('descricao', models.CharField(max_length=255)),
                ('nivel', models.IntegerField(choices=[(1, 'Baixo'), (2, 'Médio'), (3, 'Avançado')], default=(2, 'Médio'))),
            ],
        ),
    ]
