# Generated by Django 4.1.2 on 2022-10-15 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0005_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
