# Generated by Django 4.1.2 on 2022-10-15 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0007_aluno_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='email',
            field=models.EmailField(max_length=30),
        ),
    ]
